v6manager/accounts/urls.py
# coding:utf8
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^login/$', 'accounts.views.login', name='login'),
    url(r'^logout/$', 'accounts.views.logout', name='logout'),
)

v6manager/picmanager/urls.py
# coding:utf8
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^upload/$', 'picmanager.views.upload', name='upload'),
    url(r'^ctrl/$', 'picmanager.views.ctrl', name='ctrl'),
)

v6manager/v6manager/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'picmanager.views.ctrl', name="home"),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^picmanager/', include('picmanager.urls')),
)

v6manager/accounts/models.py
from django.db import models

# Create your models here.

v6manager/picmanager/models.py
# coding: utf8
from django.db import models

# Create your models here.
class Pictures(models.Model):
    p_name = models.CharField(max_length=100)  # 图片名称
    p_position = models.CharField(max_length=10)  # 显示位置
    p_explain = models.CharField(max_length=100)  # 图片描述
    p_href = models.CharField(max_length=200)  # 图片连接
    p_uploaddate = models.DateField(blank=True)  # 上传时间
    p_show = models.BooleanField(default=False)  # 是否显示
    p_img = models.CharField(max_length=200, blank=False)  # 图片地址
    show_id = models.IntegerField()  # 显示顺序

    class Meta:
        db_table = 'pictures'

v6manager/picmanager/forms.py
# coding=utf-8

import os
from django import forms


class ImgForm(forms.Form):

    '''只负责图片上传以及控制位置，是否显示别处处理。
    '''
    position = forms.ChoiceField(label=u"显示位置:",
                                 choices=[('top', u'顶部通知'),
                                          ('top_flash', u'顶部动画通知'),
                                          ('center', u'中间推广')]
                                 )
    image = forms.ImageField(required=True, label=u"请选择图片:",
                             error_messages={'required': '图片不可为空.'})
    explain = forms.CharField(label=u"图片说明",
                              error_messages={'required': '图片说明不可为空.'})
    href = forms.CharField(label=u"图片连接", required=False)
    show_id = forms.IntegerField(label=u"图片顺序", required=True)

    def clean_image(self):
        data = self.cleaned_data['image']
        file_name_suffix = os.path.splitext(data.name)[1].lower()
        if file_name_suffix not in ['.jpg', '.png', '.bmp', '.gif']:
            raise forms.ValidationError(u"禁止上传此种文件类型。")
        return data

v6manager/accounts/views.py
# coding: utf8
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login, authenticate, logout as auth_logout
from django.http import HttpResponseRedirect

def login(request):
    err_msg = ''
    if request.user.is_authenticated():
        return HttpResponseRedirect('/picmanager/ctrl/')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            auth_login(request, user)
            return HttpResponseRedirect('/picmanager/ctrl/')
        else:
            err_msg = u"用户名或者密码错误！"
    return render(request, 'accounts/login.html', {'err_msg': err_msg})

@login_required
def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/accounts/login/')

v6manager/picmanager/views.py
# coding: utf8
import time

from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from .models import Pictures
from .forms import ImgForm

@login_required
def ctrl(request):
    if request.method == "POST":
        post = request.POST
        set_show(post)
        tp = Pictures.objects.filter(p_position="top").order_by('-id')[:3]
        tfp = Pictures.objects.filter(p_position="top_flash").order_by('-id')[:3]
        # 配置显示的图片
        cp_1 = Pictures.objects.filter(p_position="center", p_show=1).order_by('show_id')
        # 以前的图片
        cp_0 = Pictures.objects.filter(p_position="center", p_show=0).order_by('-id')[:10]
        return render(request, "picmanager/ctrl.html",
                {"tp": tp, "cp_1": cp_1, 'cp_0': cp_0,
                 'tfp': tfp, "msg": "修改成功！"})
    else:
        tp = Pictures.objects.filter(p_position="top").order_by('-id')[:3]
        tfp = Pictures.objects.filter(p_position="top_flash").order_by('-id')[:3]
        # 配置显示的图片
        cp_1 = Pictures.objects.filter(p_position="center", p_show=1).order_by('show_id')
        # 以前的图片
        cp_0 = Pictures.objects.filter(p_position="center", p_show=0).order_by('-id')[:10]
    return render(request, 'picmanager/ctrl.html', {'tp': tp, 'cp_1': cp_1,
                                                    'cp_0': cp_0, 'tfp': tfp})

def set_show(show_list):
    """
    设置图片是否显示, 还有图片显示顺序
    """
    # 设置图片显示顺序
    for k, v in show_list.iteritems():
        img_id = k[8:]
        if img_id:
            flag = img_id.isdigit()
            if flag:
                pic = Pictures.objects.get(pk=img_id)
                pic.show_id = v
                pic.save()
    # 初始化所有图片为不显示
    pics = Pictures.objects.filter(p_show=True)
    for each_pic in pics:
        each_pic.p_show = False
        each_pic.save()
    # 设置需要显示的图片
    show_list = list(show_list)
    for x in show_list:
        if not x.startswith("show_") and not x.startswith("csrf"):
            pic = Pictures.objects.get(pk=x)
            pic.p_show = True
            pic.save()

@login_required
def upload(request):
    if request.method == 'POST':
        form = ImgForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            position = data.get('position', '')
            explain = data.get('explain', '')
            href = data.get('href', '#')
            show_id = data.get('show_id', 0)
            img = data.get('image', '')
            name = img.name
            uploaddate = time.strftime("%Y-%m-%d")

            new_pic = Pictures()
            new_pic.p_name = name
            new_pic.p_position = position
            new_pic.p_explain = explain
            new_pic.p_href = href or '#'
            new_pic.p_uploaddate = uploaddate
            new_pic.show_id = show_id
            new_pic.save()

            img_name = '%s_%s' % (new_pic.id, name)
            url = 'http://localhost/v5media/notifyimg/%s' % img_name
            new_pic.p_img = url
            new_pic.save()

            write_pic(img, img_name)
            return render(request, 'picmanager/upload.html',
                          {'form': form, 'msg': '上传成功'})
    else:
        form = ImgForm()
    return render(request, 'picmanager/upload.html', {'form': form})

def write_pic(img, img_name):
    with open('/home/chenhj/test/imgs/%s' % img_name, 'wb+') as destination:
        for chunk in img.chunks():
            destination.write(chunk)

v6manager/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block title %}
    <title>登陆</title>
{% endblock %}

{% block body %}
<p>{{err_msg}}</p>
<form class="form-inline" action="#" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="usernameInput">用户名: </label>
        <input type="text" name="username" class="form-control" id="usernameInput" placeholder="请输入用户名" />
    </div>
    <div class="form-group">
        <label for="passwordInput">密码: </label>
        <input type="password" name="password" class="form-control" id="passwordInput" placeholder="请输入密码" />
    </div>
    <input type="reset" value="重置" class="btn btn-default"/>
    <input type="submit" value="登陆" class="btn btn-default"/>
</form>
{% endblock %}

v6manager/picmanager/templates/picmanager/ctrl.html
{% extends "base.html" %}
{% block title %}
  <title>管理图片</title>
{% endblock %}

{% block body %}
<form action="{% url 'ctrl'%}" method="post">{% csrf_token %}
    {% if msg %}
    <b><p style="color:red; font-size:20px">{{msg}}</p></b>
    {% endif %}
    <h3>顶部通知</h3>
    <table border="1" class="table table-bordered">
        <tr>
            <th>名称</th>
            <th>说明</th>
            <th>连接</th>
            <th>上传时间</th>
            <th>是否显示</th>
        </tr>
        {% for top in tp %}
        <tr>
            <td>{{ top.p_name }}</td>
            <td>{{ top.p_explain }}</td>
            <td>{{ top.p_href }}</td>
            <td>{{ top.p_uploaddate }}</td>
            <td><input type="checkbox" name={{ top.id }} {% if top.p_show %} checked="True"  {% endif %}/></td>
        </tr>
        {% endfor %}
    </table>

    <h3>顶部动画通知</h3>
    <table border="1" class="table table-bordered">
        <tr>
            <th>名称</th>
            <th>说明</th>
            <th>连接</th>
            <th>上传时间</th>
            <th>是否显示</th>
        </tr>
        {% for top_flash in tfp %}
        <tr>
            <td>{{ top_flash.p_name }}</td>
            <td>{{ top_flash.p_explain }}</td>
            <td>{{ top_flash.p_href }}</td>
            <td>{{ top_flash.p_uploaddate }}</td>
            <td><input type="checkbox" name={{ top_flash.id }} {% if top_flash.p_show %} checked="True"  {% endif %}/></td>
        </tr>
        {% endfor %}
    </table>

    <h3>中间推广</h3>
    <table border="1" class="table table-bordered">
        <tr>
            <th>名称</th>
            <th>说明</th>
            <th>连接</th>
            <th>上传时间</th>
            <th>显示顺序</th>
            <th>是否显示</th>
        </tr>
        {% for cen in cp_1 %}
        <tr>
            <td>{{ cen.p_name }}</td>
            <td>{{ cen.p_explain }}</td>
            <td>{{ cen.p_href }}</td>
            <td>{{ cen.p_uploaddate }}</td>
            <td>
                <select name="show_id_{{cen.id}}">
                    <option value="1" {% if cen.show_id == 1 %} selected {% endif %}>1</option>
                    <option value="2" {% if cen.show_id == 2 %} selected {% endif %}>2</option>
                    <option value="3" {% if cen.show_id == 3 %} selected {% endif %}>3</option>
                    <option value="4" {% if cen.show_id == 4 %} selected {% endif %}>4</option>
                    <option value="5" {% if cen.show_id == 5 %} selected {% endif %}>5</option>
                </select>
            </td>
            <td><input type="checkbox" name={{ cen.id }} {% if cen.p_show %} checked="True"  {% endif %}/></td>
        </tr>
        {% endfor %}
        {% for cen in cp_0 %}
        <tr>
            <td>{{ cen.p_name }}</td>
            <td>{{ cen.p_explain }}</td>
            <td>{{ cen.p_href }}</td>
            <td>{{ cen.p_uploaddate }}</td>
            <td>
                <select name="show_id_{{cen.id}}">
                    <option value="1" {% if cen.show_id == 1 %} selected {% endif %}>1</option>
                    <option value="2" {% if cen.show_id == 2 %} selected {% endif %}>2</option>
                    <option value="3" {% if cen.show_id == 3 %} selected {% endif %}>3</option>
                    <option value="4" {% if cen.show_id == 4 %} selected {% endif %}>4</option>
                    <option value="5" {% if cen.show_id == 5 %} selected {% endif %}>5</option>
                </select>
            </td>
            <td><input type="checkbox" name={{ cen.id }} {% if cen.p_show %} checked="True"  {% endif %}/></td>
        </tr>
        {% endfor %}
    </table>
    <input class="btn btn-danger" type="submit" value="确认修改" />
</form>
{% endblock %}

v6manager/picmanager/templates/picmanager/upload.html
{% extends "base.html" %}
{% block title %}
    <title>上传图片</title>
{% endblock %}

{% block body %}
<h3>上传图片</h3>
<div class="h3_bg"></div>
<div class="container">

    {% if msg %}
        <b><p style="color:red; font-size:20px">{{msg}}</p></b>
    {% endif %}

    <b><p style="color:red; font-size:20px">！图片名称请不要包含中文！</p></b>
    <b><p>{{form.errors}}</p></b>
    <div class="file-box">
        <form enctype="multipart/form-data" method="post" action="{% url 'upload'%}">
            {% csrf_token %}
            <div class="form-group">
                <label for="positionInput">显示位置:</label>
                <select name="position" class="form-control">
                    <option value="top">顶部通知</option>
                    <option value="top_flash">顶部动画通知</option>
                    <option value="center">中间推广</option>
                </select>
            </div>
            
            <div class="form-group">
                <label for="imageInput">请选择图片:</label>
                <input type="file" required id="id_image" class="file" name="image">
            </div>

            <div class="form-group">
                <label for="explainInput">图片说明:</label>
                <input type="text" required class="form-control" name="explain" id="explainInput" placeholder="请输入图片说明">
            </div>

            <div class="form-group">
                <label for="hrefInput">图片链接:</label>
                <input type="text" class="form-control" name="href" id="hrefInput" placeholder="请输入图片链接">
            </div>

            <div class="form-group">
              <label for="explainInput">图片顺序:</label>
              <input type="number" value="1" name="show_id" id="id_show_id">
            </div>
            <input type="submit" class="btn btn-danger" value="上传图片">
        </form>
    </div>
</div>
{% endblock %}

v6manager/v6manager/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="cn">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
        {% block title %}
        <title>v6后台管理系统</title>
        {% endblock %}
        {% block import %}
        {% endblock %}
    </head>
    <body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'home' %}">
          <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
      </a>
    </div>
    {% if request.user.is_authenticated %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'upload' %}">上传图片</a></li>
              <li><a href="{% url 'ctrl' %}">管理图片</a></li>
            <li><a href="{% url 'logout' %}">登出</a></li>
          </ul>
        </div>
  {% endif %}
  </div>
</nav>

        {% block body %}
        {% endblock %}
        {% block footjs %}
        {% endblock %}
    </body>
</html>